@extends('layouts.blog')
@section('blog-content')
    <h1>{{ $entry }}</h1> ({{ $page }})
    <div class="blog__entry">
        <div class="blog__sidebar">
            <ul>
                <li>Foo</li>
                <li>Bar</li>
                <li>Baz</li>
            </ul>
        </div>
        <div class="blog__content">

            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam consectetur lacinia enim ut venenatis. Vivamus dictum eros nisl, eu gravida odio blandit eu. Suspendisse elementum turpis quis metus vehicula elementum at in purus. Morbi cursus, odio eu fringilla dignissim, ipsum lectus dignissim neque, non molestie elit sem a ligula. Vestibulum quis fringilla tortor. Proin fermentum diam vel libero euismod posuere. Integer sodales dolor sed sem dignissim lacinia. Integer tellus nisi, varius sed mollis sit amet, finibus et leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

            Phasellus fermentum dapibus interdum. Donec vestibulum nisl massa, eu tristique massa sagittis sit amet. Sed elementum, justo nec gravida pretium, massa quam porttitor diam, a varius tellus odio ut urna. Cras rhoncus sem et varius egestas. Pellentesque vel fringilla sapien, at imperdiet mi. Sed nec tincidunt augue. Pellentesque aliquet sem non purus congue, eget sollicitudin metus rhoncus. Phasellus imperdiet rutrum ante, a aliquet est congue a. Donec ultrices enim ut semper consequat. Donec pellentesque risus sit amet massa rutrum, non tristique mauris tristique. Proin tincidunt pharetra tellus. Sed magna lorem, hendrerit id sodales a, lacinia eget libero. Morbi vitae diam eget arcu hendrerit scelerisque in in odio. Donec malesuada tortor id nibh hendrerit suscipit.

            Sed pellentesque arcu at sapien auctor, vitae consequat velit varius. Sed tincidunt tortor sed tellus imperdiet viverra. Suspendisse nec rhoncus est, eu luctus purus. Aliquam iaculis justo felis, id auctor lectus semper eu. Vestibulum ac neque porta orci eleifend pulvinar. Integer sagittis convallis felis ac fermentum. Sed luctus eu ipsum ac tincidunt. Aliquam lacinia nunc id porta dictum. Aliquam pharetra lacus vulputate dignissim faucibus. Nullam at tempus nisi. Nulla nec accumsan libero. Vestibulum interdum dolor a ante lobortis, vel luctus ligula iaculis.

            Nunc et dignissim lorem. Pellentesque elementum mauris viverra, auctor libero sed, varius nisi. Donec laoreet sit amet arcu nec ultricies. Phasellus pharetra placerat enim id accumsan. Duis laoreet aliquam porta. Morbi feugiat dignissim leo, quis cursus erat hendrerit ac. Ut risus enim, ultricies ac elit eu, pharetra aliquam libero. Ut nec mi sed quam eleifend dapibus. Phasellus eu arcu pretium, tincidunt libero et, imperdiet risus. Nullam gravida efficitur ante sed tincidunt. Proin ut sapien vitae ipsum venenatis sollicitudin nec vitae libero. Donec facilisis est non nunc congue, a accumsan dui viverra.

            Praesent quis diam euismod, convallis orci ut, euismod felis. Donec in felis eu eros ultricies consequat ac id ligula. Donec eu aliquet eros. Curabitur mattis luctus neque, quis luctus nunc pulvinar ut. Nulla sollicitudin vehicula ex ut convallis. Sed at orci sollicitudin, tincidunt ante vitae, feugiat felis. Suspendisse efficitur ultricies sodales. Aliquam erat volutpat. Integer semper, urna sed mollis mattis, quam tortor imperdiet orci, a auctor arcu nunc et sapien. Phasellus neque ex, fermentum nec ultricies a, molestie at ante. Cras rhoncus orci ut turpis sagittis vulputate. Etiam bibendum nisl nibh, sed euismod arcu facilisis vel. Mauris ornare enim lacus, eget varius purus tincidunt a.

            Cras metus turpis, efficitur eget facilisis eget, tincidunt et risus. Mauris dignissim lorem sed tellus gravida vehicula. Praesent quis orci a dui dictum eleifend ac non nibh. Cras vel congue nunc. Maecenas non dolor viverra massa congue congue egestas a lacus. Fusce at lectus id risus euismod laoreet. Maecenas non sollicitudin orci, eget commodo neque. Maecenas id nibh consequat, porta risus eu, varius sem. Maecenas eu felis a lorem pretium ullamcorper. Praesent aliquam eros dolor, in mollis ex bibendum vel.

            Sed sodales tellus est, non ultricies velit semper vel. Aenean accumsan nisl risus, quis luctus nisl lacinia nec. Etiam mattis, eros non pulvinar placerat, urna dui pharetra arcu, non lacinia risus lacus in tellus. Integer cursus efficitur quam et semper. In id est suscipit, ornare massa sed, rutrum sapien. Phasellus vestibulum vel ex quis auctor. Cras eget malesuada dui. Etiam ultrices diam vitae tincidunt scelerisque. Nam sollicitudin risus eu commodo faucibus. Ut non diam vitae tortor aliquam ornare.

            In sodales purus sapien, non sagittis quam pretium ac. Nulla interdum nulla eleifend erat ornare ullamcorper. Ut ornare fringilla euismod. Nulla facilisi. Duis malesuada viverra quam quis facilisis. Maecenas quis venenatis nisl, vitae faucibus massa. Etiam cursus lobortis mi sed fringilla. Aliquam sed maximus velit, ac accumsan risus. Ut tincidunt at nisi eget pulvinar. Aliquam justo purus, euismod ut purus at, vestibulum auctor dolor. Praesent interdum, mi in finibus tincidunt, enim metus volutpat massa, nec elementum dui lacus non velit.

            Curabitur posuere augue a iaculis mollis. Nullam et dictum ipsum, ac imperdiet justo. Vivamus varius lacus metus, ut pellentesque purus commodo sed. Quisque hendrerit vel magna sed posuere. Suspendisse maximus enim vel porta interdum. Vestibulum ut ornare ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut mattis lacus quis risus tristique accumsan. Sed ac velit consectetur, vulputate lacus et, vehicula elit. Vivamus feugiat eget libero vitae vulputate. In quam turpis, egestas et felis vitae, porta dapibus risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla ipsum risus, mollis vitae lacinia vel, faucibus in est. Aliquam at suscipit augue.

            Integer sit amet fringilla dui. In hac habitasse platea dictumst. Aliquam sit amet dictum felis. Quisque non dapibus ligula. Duis vel fringilla lectus. Aliquam tempus dapibus efficitur. Sed purus massa, aliquet eu consectetur quis, viverra in nibh. Morbi et scelerisque purus. Suspendisse porta eu massa sed consectetur. Nam vel maximus ante. Nulla et libero non leo pharetra elementum ac vitae mi. Nunc congue ex sit amet libero condimentum, vitae cursus felis condimentum. Maecenas molestie metus quis diam fermentum, in faucibus augue elementum. Vivamus auctor orci eu nisi porta porta. Donec viverra tempor ultrices.

            Aenean condimentum varius eros condimentum accumsan. Nullam vulputate leo fringilla odio luctus, quis eleifend augue hendrerit. In iaculis, risus vel condimentum porta, massa odio sodales nibh, vel rhoncus neque sapien non justo. Vivamus sed finibus ante, at pretium ipsum. Suspendisse pulvinar quis nisl ut venenatis. Morbi non hendrerit lorem, ut egestas dolor. Quisque a justo elementum, sagittis quam et, faucibus nulla. Quisque tristique aliquet nisi et laoreet. Quisque cursus erat sit amet quam condimentum, non rhoncus lorem tristique.

            Aliquam tincidunt vel risus et ullamcorper. Fusce tempor fermentum mauris id tempor. Nunc dignissim tortor a risus rutrum vulputate. Phasellus scelerisque condimentum augue sit amet consectetur. Curabitur vulputate lectus purus, eu vulputate tortor laoreet ut. Etiam lacinia auctor libero sit amet tincidunt. Cras diam turpis, dapibus at ultricies ac, maximus ut sapien. Pellentesque dictum, arcu et lacinia tempus, lorem magna placerat lectus, posuere lobortis purus quam sed nisl. Maecenas in posuere sem, eget rhoncus ex. Aenean lacus odio, aliquam at viverra nec, lobortis in massa. Etiam fringilla risus nisi.

            Mauris aliquam nunc velit, sit amet vehicula urna ultrices sed. Quisque vehicula tincidunt magna et tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at pulvinar magna. Donec risus nibh, elementum ut aliquam at, lobortis nec urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed non ex turpis. Vivamus consectetur dui et dignissim semper. Mauris aliquet metus id nibh tristique mollis. Etiam elementum sem felis, ut efficitur odio porttitor sed. Nunc tellus turpis, pharetra quis iaculis nec, molestie vel orci. Nam facilisis, odio eu fermentum aliquet, ipsum felis pulvinar est, at auctor nisi massa tincidunt nunc. Curabitur pulvinar eleifend libero.

            Integer et hendrerit felis, non elementum urna. Donec iaculis volutpat interdum. Morbi semper nisl ut arcu imperdiet vestibulum. Duis ex mi, bibendum eu neque et, ultricies congue sem. Nam dictum eros id congue laoreet. Integer sit amet ipsum eu sem blandit gravida. Sed at varius ligula, eget sodales quam. In tristique, odio vitae cursus sollicitudin, turpis erat malesuada leo, in consequat diam metus ac eros. Duis scelerisque odio a pulvinar sollicitudin.

            Cras ac condimentum sem. Aenean semper dictum libero, eu tempus libero congue non. Suspendisse scelerisque eros nibh, non viverra mauris venenatis sollicitudin. Fusce vitae lobortis ipsum. Nullam malesuada nisl mi, non interdum ante malesuada bibendum. Nam placerat urna maximus enim semper, quis eleifend justo rutrum. Suspendisse ligula augue, tincidunt ac mattis in, pharetra sit amet sem. Pellentesque convallis turpis quam, quis tempor ex malesuada et. Duis eu erat nisi. Praesent in lobortis diam. Donec accumsan enim vel vestibulum pretium. Sed placerat, nunc feugiat vestibulum ullamcorper, libero massa efficitur velit, eget accumsan tellus ligula volutpat enim. In hac habitasse platea dictumst. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla consequat vitae ante at hendrerit.
        </div>
    </div>
@endsection